### ISSUE TITLE
JetPack4.5-DeepStream5.1 source1_primary_detector_qat.txt does not work

### ISSUE THREAD

**Issue by SnowMasaya** [NVIDIA-AI-IOT/gesture_recognition_tlt_deepstream#3]
This branch for JetPack4.5-DeepStream5.1 but the following setting is the DeepStream 5.0.
I think it is not work.

```
ll-lib-file=/opt/nvidia/deepstream/deepstream-5.0/lib/libnvds_mot_klt.so
```

https://github.com/NVIDIA-AI-IOT/gesture_recognition_tlt_deepstream/blob/31f14b84c0adf466c4cbdf7ef17b3e063ccb812b/deployment_deepstream/egohands-deepstream-app-trtis/source1_primary_detector_qat.txt#L174

Please fix the followings

```
ll-lib-file=/opt/nvidia/deepstream/deepstream-5.1/lib/libnvds_mot_klt.so
```

**Comment by katjasrz** [comment]
Thank you, good catch! I fixed that.
