### ISSUE TITLE
Can you share the two files generated after the training phase ?

### ISSUE THREAD

**Issue by Mactemium** [NVIDIA-AI-IOT/gesture_recognition_tlt_deepstream#4]
Hello, 

I haven't been able to reproduce the training phase because I lack Nvidia gpus. I have a jetson nano and I would like to use the final model for inference. However, I miss the two files that are supposed to be generated after the training phase :

calibration_qat.bin
resnet34_detector_qat.etlt

Without those two, I can't run inference, could you please provide them ?

Thank you in advance.

**Comment by katjasrz** [comment]
Unfortunately, we cannot share the trained models.
