### ISSUE TITLE
[DeepStream6.1] Error: gesture_recognition_tlt_deepstream

### ISSUE THREAD

**Issue by mat-macnica** [NVIDIA-AI-IOT/gesture_recognition_tlt_deepstream#7]
Hi,

I’v already run below github project with JetPack4.5.1 and Deepstream5.1 on Jetson Xavier NX.
And I try to run below github project with JetPack5.0.1 and Deepstream6.1 on Jetson Xavier NX.

[GitHub](https://github.com/NVIDIA-AI-IOT/gesture_recognition_tlt_deepstream)

[GitHub - NVIDIA-AI-IOT/gesture_recognition_tlt_deepstream: A project...](https://github.com/NVIDIA-AI-IOT/gesture_recognition_tlt_deepstream)
A project demonstrating how to train your own gesture recognition deep learning pipeline. We start with a pre-trained detection model, repurpose it for hand detection using Transfer Learning Toolki...

But we found errors like below;

![hand](https://user-images.githubusercontent.com/92834689/182501412-2f43c2b2-04f5-45f5-b1eb-2ca3bef27010.png)

I also check below migration guides.
But it seems not to be clue about this Error.
https://docs.nvidia.com/metropolis/deepstream/6.0/dev-guide/text/DS_Application_migration.html
https://docs.nvidia.com/metropolis/deepstream/dev-guide/text/DS_Application_migration.html

Question:
Are there anyone success to run this github project with JetPack5.0.1 and Deepstream6.1 on JetsonNX?

I also try to build by commented out like below;
// case NV_DS_SINK_RENDER_OVERLAY:

Build Error was not found.
But we found another Error by running “deepstream-app-bbox” like below;

![err](https://user-images.githubusercontent.com/92834689/182501482-443bea98-6036-4f2e-8e7c-7e8a15283c39.png)

We would appreciate if you tell us how to solve this issue.

P.S. This post is same as below;
https://forums.developer.nvidia.com/t/deepstream6-1-build-error-gesture-recognition-tlt-deepstream/222648

Best regards,/

**Comment by katjasrz** [comment]
I would assume, the NV_DS_SINK_RENDER_OVERLAY got replaced in the newer DS version. As it doesn't affect this application, I would say it's safe to comment this.

I assume your second error is associated with nvinferserver plugin. To use it, you need to make sure that you have a Deepstream installation with Triton support. Check this page for more information: https://github.com/NVIDIA-AI-IOT/deepstream_triton_migration

Alternatively, you can use the standard nvinfer plugin for the second model as well, as in that case we used both plugins primarily for demonstration purpose.

**Comment by mat-macnica** [comment]
Hi,

Thank you very much for your kindness.
I really appreciate your help.

I'd like to check the behavior with your guide.

Best regards,

**Comment by mat-macnica** [comment]
Hi,

I can solve this problem with below link.
Thank you !
https://forums.developer.nvidia.com/t/deepstream6-1-build-error-gesture-recognition-tlt-deepstream/222648/5

**Comment by katjasrz** [comment]
I'm glad to hear that! Thanks for sharing
